### ISSUE TITLE
Wp 5.4 issue

### ISSUE THREAD

**Issue by casian96** [liip/bootstrap-blocks-wordpress-plugin#39] opened 2020-04-01 09:58 UTC
Sidebar issue after WP Core update.
<img width="231" alt="Zrzut ekranu 2020-04-1 o 11 42 48" src="https://user-images.githubusercontent.com/26876683/78124468-00351900-7410-11ea-9792-71ac26014da0.png">
<img width="482" alt="Zrzut ekranu 2020-04-1 o 11 58 26" src="https://user-images.githubusercontent.com/26876683/78124538-1c38ba80-7410-11ea-81f1-b4c19c76b87d.png">

**Comment by tschortsch** [comment] 2020-04-01 13:13
Hi @casian96. Sadly I can't reproduce this issue. Can you maybe send me your block content (from Code editor) where this issue appears?

**Comment by tschortsch** [comment] 2020-04-10 11:24
Will close this issue for now since we can't reproduce it on our side. Please try it again with v2.1.0 of this plugin.

**Closed by tschortsch** 2020-04-10 11:24 UTC
Labels: bug
